### ISSUE TITLE
ardrone_autonomy.msg

### ISSUE THREAD

**Issue by rojas70** [mikehamer/ardrone_tutorials_getting_started#1]
I have been looking at different posts, I was under the understanding that this bug had been repaired late 2013, but with a fresh git clone call, the error still is here.

ERROR: cannot launch node of type [ardrone_autonomy/ardrone_driver]: can't locate node [ardrone_driver] in package [ardrone_autonomy]
process[keyboard_controller-3]: started with pid [28502]
Traceback (most recent call last):
  File "/home/vmrguser/rosGWS/ardrone_tutorials/src/keyboard_controller.py", line 13, in <module>
    from drone_controller import BasicDroneController
  File "/home/vmrguser/rosGWS/ardrone_tutorials/src/drone_controller.py", line 17, in <module>
    from ardrone_autonomy.msg import Navdata # for receiving navdata feedback
ImportError: No module named ardrone_autonomy.msg

**Comment by cipri-tom** [comment]
Hi,
Have you managed to solve this? Thanks!

**Comment by malharjajoo** [comment]
Hey
similar issue, any solutions ?

**Comment by cipri-tom** [comment]
@malharjajoo my memory is weak, but I think the message types need to be defined in a subfolder that is in the python path (or in the current directory). I don't have access to the laptop where I played with this, but if you don't find a solution, ping me back after 9th Jan and I'll check out how I structured the folders so that the `ardrone_autonomy.msg` module can be found.
